logging:
  level:
    root: warn
    me.sonam: debug

info:
  app:
    name: Springboot me.sonam.account.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

openissuer:
  trusted-issuer-host-suffixes: ${TRUSTED_ISSUER_HOST_SUFFIXES:openissuer.test,openissuer.com}

server:
  port: 8080

spring:
  application:
    name: user-rest-service
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode:  ${DB_SSLMODE}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI}

authentication-rest-service:
  root: ${AUTHENTICATION_REST_SERVICE}
  context: ${authentication-rest-service.root}/authentications

account-rest-service:
  root: ${ACCOUNT_REST_SERVICE}
  context: ${account-rest-service.root}/accounts

organization-rest-service:
  root: ${ORGANIZATION_REST_SERVICE}
  context: ${organization-rest-service.root}/organizations

role-rest-service:
  root: ${ROLE_REST_SERVICE}
  context: ${role-rest-service.root}/roles

auth-server:
  root: http://authorization-server
  context-path:
  oauth2token:
    path: /oauth2/token
    grantType: client_credentials

permitpath:
  - path: /users/api/health/*
    httpMethods: GET

requestFilters:
  - in:
    out:
    inHttpMethods:
    accessToken:
      option: request
      scopes: message.read
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}

tokenExpireSeconds: 180
