# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
server:
  port: 8084

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: user
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

ACCOUNT_REST_SERVICE: http://account-rest-service
AUTHENTICATION_REST_SERVICE: http://authentication-rest-service

ISSUER_URI: http://api-gateway:8080/issuer
JWT_SET_URI: http://api-gateway:8080/issuer/.well-known/jwks.json
OAUTH_AUDIENCES: oauth-client

REQUEST_SCOPES: message.read message.write
BASE64_CLIENT_ID_SECRET: b2F1dGgtY2xpZW50Om9hdXRoLXNlY3JldA==


spring:
  cloud:
    kubernetes:
      enabled: false