# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
server:
  port: 8084

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: user
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

eureka:
  client:
    enabled: true

DEFAULT_ZONE: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

# jwt-rest-service on port 8081 local server
JWT_REST_SERVICE: http://jwt-rest-service
APPLICATION_REST_SERVICE: http://application-rest-service
ACCOUNT_REST_SERVICE: http://account-rest-service
AUTHENTICATION_REST_SERVICE: http://authentication-rest-service

hmacKey:
  clientId: user-rest-service
  algorithm: HmacMD5
  secretKey: mysecret