# this profile is activated by kubernetes dependencies
spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        namespaces:
           - backend
        include-not-ready-addresses: true
eureka:
  client:
      enabled: false

#        args: ["-Dspring.profiles.active=kubernetes",
#  "-Dspring.cloud.kubernetes.discovery.discovery-server-url
#  =http://spring-cloud-kubernetes-discoveryserver.default.svc.cluster.local",
#"-Dspring.cloud.kubernetes.discovery.enabled=true", "org.springframework.boot.loader.JarLauncher"]
