on:
  push:
jobs:

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Export project name
        run: export PROJECT_NAME=$(echo ${{ github.repository }} | cut -d / -f2); echo $PROJECT_NAME

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Temurin JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build Docker image and push to ghcr.io registry
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{github.repository}}:latest
          secrets: |
            USERNAME=${{ github.actor }}
            PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
